devices:
  - id: 1
    parameters:
      current:
        min: 100.0
        max: 1500.0
        protection_threshold: 1800.0
        divider: 10
        units: "mA"
      frequency:
        min: 10.0
        max: 200.0
        divider: 10
        units: "Hz"
      duration:
        min: 1.0
        max: 10.0
        divider: 10
        units: "ms"
    tec_commands:
      tec_temp:
        min: 10.0
        max: 40.0
        divider: 100
        units: "°C"
      tec_current:
        limit: 1.0
        divider: 10
        units: "A"
    state_commands:
      state_of_device:
        bits:
          "1":
            name: "operation state"
            states:
              "0": "stopped"
              "1": "started"
    timing:
      response_delay_ms: 10
      processing_delay_ms: 5
      tec_settling_time_ms: 1000  